In [1]:
import os
import numpy as np
from matplotlib import pyplot as plt
import cv2
from numpy import nan

In [2]:
def conv(im, A):
    
    H, W = im.shape
    h, w = A.shape
    B = np.zeros((H-h+1,W-w+1))
    
    for x in range((H-h+1)*(W-w+1)):
            r = x // (W-w+1)
            c = x % (W-w+1)
            B[r,c] = np.sum(np.multiply(A,im[r:r+h,c:c+w]))
    
       
    return B

In [3]:
# Write your code here
sobel_x = np.array([[-1, 0, 1], [-2, 0, 2], [-1, 0, 1]])
sobel_y = np.array([[-1, -2, -1], [0, 0, 0], [1, 2, 1]])

print(sobel_x)
print(sobel_y)

[[-1  0  1]
 [-2  0  2]
 [-1  0  1]]
[[-1 -2 -1]
 [ 0  0  0]
 [ 1  2  1]]


In [7]:

Image = np.array([[-3,1,7,-1,21],[12,13,10,9,14],[19,8,15,18,24],[3,-7,-7,-5,-6],[9,8,-3,7,2]])

Image

array([[-3,  1,  7, -1, 21],
       [12, 13, 10,  9, 14],
       [19,  8, 15, 18, 24],
       [ 3, -7, -7, -5, -6],
       [ 9,  8, -3,  7,  2]])

In [9]:
grad_x = conv(Image,sobel_x)
grad_y = conv(Image,sobel_y)

print(grad_x)
print(grad_y)

[[  2.   0.  31.]
 [-20.  18.  23.]
 [-36.  13.  16.]]
[[ 44.  42.  49.]
 [-66. -68. -65.]
 [-28. -47. -62.]]


In [12]:
kernel = np.array([[-1,1,2],[-1,1,1],[-1,-1,-1]])
print(kernel)

Image = np.array([[1,3,-1,5,6],
                 [2,2,8,6,8],
                 [2,-1,7,2,8],
                 [-1,0,2,-1,2],
                 [4,4,1,3,1]])
print(Image)

print(conv(np.ones((6,9)),np.ones((6,6))))

[[-1  1  2]
 [-1  1  1]
 [-1 -1 -1]]
[[ 1  3 -1  5  6]
 [ 2  2  8  6  8]
 [ 2 -1  7  2  8]
 [-1  0  2 -1  2]
 [ 4  4  1  3  1]]
[[36. 36. 36. 36.]]
